### ISSUE TITLE
Conda env creation errors on MacOS

### ISSUE THREAD

**Issue by benrhodes26** [ASK-Berkeley/EScAIP#9]
Thanks for the great paper!

When running `mamba env create -f env.yml`, I hit:

```
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ pytorch-cuda =12.1 * does not exist (perhaps a typo or a missing channel);
    └─ xformers =* * does not exist (perhaps a typo or a missing channel).
```

Running on MacOS (Version 14.6.1) with versions:
```
conda 23.1.0
mamba 2.0.4
```

**Comment by benrhodes26** [comment]
I didn't hit this error on `Debian 5.10.221-1 (2024-07-14) x86_64 GNU/Linux`, so it's presumably MacOS specific.

**Comment by EricZQu** [comment]
Hey, thank you for trying our model! Unfortunately, we don't have plans for MacOS support. A lot of operations are based on CUDA kernels, so the best platform to run the model would be a Nvidia GPU + Linux. You can follow the install instructions for CPU here (https://fair-chem.github.io/core/install.html) to try it on MacOS, but it's untested and could be extremely slow.
